name: test-power-method
on:
 push


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
# prerequisites
      - run : pip install -r requirements.txt
# python itself is already installed in the ubuntu image
# run the tests
      - name: Run Tests
        run: |
              pytest test_power_method.py



